### ISSUE TITLE
When will the latest version be available in npm?

### ISSUE THREAD

**Issue by adiAtMiddleware** [noflo/noflo-test#11]
We are trying to use this in our project. Latest version in npm is 0.0.7.

**Comment by 7yl4r** [comment]
It's been almost a year, but the npm version and the version in this repository are both 0.0.7. Am I missing something?

**Comment by bergie** [comment]
We have 0.1.0 up now, and will release 0.2.0 soon. But really, please use https://github.com/flowbased/fbp-spec instead
