### ISSUE TITLE
first test always reports as async

### ISSUE THREAD

**Issue by forresto** [noflo/noflo-test#13]
These are the same:

```
  Dispatch
    When receiving a graph
      ✓ Should send the graph in a `new graph` group. (1613ms)
    When receiving a graph 2
      ✓ Should send the graph in a `new graph` group. 
```

The first is [timing out sometimes](https://travis-ci.org/forresto/the-graph-flux/builds/42015635#L148) (>2000ms) on Travis, causing false fails.

**Comment by bergie** [comment]
This is because of component loading on first test
